#!/usr/bin/env python3
"""
Sentinel Prime - DNS Anomaly Detection Module
Detects DGA (Domain Generation Algorithm) domains, DNS tunneling, and suspicious DNS patterns.

Created by: Priya Sharma (Backend Engineer)
Ticket: TICKET-0007 (Phase 2)
"""

import re
import math
import logging
from typing import Dict, List, Optional
from datetime import datetime, timedelta
from collections import defaultdict

logger = logging.getLogger('sentinel-dns')

class DNSAnomalyDetector:
    """
    Detects malicious DNS activity including:
    - DGA (Domain Generation Algorithm) domains
    - DNS tunneling (data exfiltration via DNS)
    - Suspicious query patterns
    - Known malicious domains
    """
    
    def __init__(self):
        # DGA detection thresholds
        self.entropy_threshold = 3.5  # High entropy suggests DGA
        self.consonant_ratio_threshold = 0.7  # Unusual consonant patterns
        self.vowel_ratio_threshold = 0.1  # Too few vowels
        self.length_threshold = 20  # Unusually long domains
        
        # DNS tunneling detection
        self.subdomain_length_threshold = 50  # Very long subdomains
        self.query_rate_threshold = 100  # Queries per minute per device
        self.txt_record_threshold = 20  # Excessive TXT record queries
        
        # Tracking
        self.device_query_counts = defaultdict(int)
        self.device_query_times = defaultdict(list)
        self.domain_cache = {}
        
        # Load DGA wordlists (would load from file in production)
        self.common_words = set([
            'google', 'facebook', 'amazon', 'microsoft', 'apple',
            'netflix', 'youtube', 'twitter', 'github', 'stackoverflow'
        ])
    
    def calculate_entropy(self, text: str) -> float:
        """Calculate Shannon entropy of a string."""
        if not text:
            return 0.0
        
        prob = [float(text.count(c)) / len(text) for c in set(text)]
        return -sum(p * math.log2(p) for p in prob if p > 0)
    
    def calculate_consonant_ratio(self, text: str) -> float:
        """Calculate ratio of consonants to total characters."""
        vowels = set('aeiouAEIOU')
        consonants = sum(1 for c in text if c.isalpha() and c not in vowels)
        total_letters = sum(1 for c in text if c.isalpha())
        return consonants / total_letters if total_letters > 0 else 0.0
    
    def calculate_vowel_ratio(self, text: str) -> float:
        """Calculate ratio of vowels to total characters."""
        vowels = set('aeiouAEIOU')
        vowel_count = sum(1 for c in text if c in vowels)
        total_letters = sum(1 for c in text if c.isalpha())
        return vowel_count / total_letters if total_letters > 0 else 0.0
    
    def extract_domain_parts(self, domain: str) -> Dict[str, str]:
        """Extract subdomain, domain, and TLD from full domain."""
        parts = domain.rstrip('.').split('.')
        
        if len(parts) >= 2:
            tld = parts[-1]
            main_domain = parts[-2]
            subdomain = '.'.join(parts[:-2]) if len(parts) > 2 else ''
            
            return {
                'full': domain,
                'subdomain': subdomain,
                'domain': main_domain,
                'tld': tld,
                'sld': f"{main_domain}.{tld}"  # Second-level domain
            }
        return {'full': domain, 'subdomain': '', 'domain': domain, 'tld': ''}
    
    def detect_dga_domain(self, domain: str) -> Optional[Dict]:
        """
        Detect if domain is likely generated by DGA.
        
        Returns:
            Dict with detection details if DGA suspected, None otherwise
        """
        parts = self.extract_domain_parts(domain)
        domain_name = parts['domain'].lower()
        
        # Skip common legitimate domains
        if domain_name in self.common_words:
            return None
        
        # Check entropy
        entropy = self.calculate_entropy(domain_name)
        if entropy > self.entropy_threshold:
            return {
                'type': 'dga_detected',
                'domain': domain,
                'reason': f'High entropy ({entropy:.2f} > {self.entropy_threshold})',
                'confidence': min(1.0, entropy / 5.0),
                'indicators': {
                    'entropy': entropy,
                    'length': len(domain_name),
                    'consonant_ratio': self.calculate_consonant_ratio(domain_name),
                    'vowel_ratio': self.calculate_vowel_ratio(domain_name)
                }
            }
        
        # Check consonant/vowel ratio
        consonant_ratio = self.calculate_consonant_ratio(domain_name)
        vowel_ratio = self.calculate_vowel_ratio(domain_name)
        
        if consonant_ratio > self.consonant_ratio_threshold or vowel_ratio < self.vowel_ratio_threshold:
            return {
                'type': 'dga_detected',
                'domain': domain,
                'reason': f'Unusual character distribution (consonants: {consonant_ratio:.2f}, vowels: {vowel_ratio:.2f})',
                'confidence': max(consonant_ratio, 1.0 - vowel_ratio),
                'indicators': {
                    'entropy': entropy,
                    'length': len(domain_name),
                    'consonant_ratio': consonant_ratio,
                    'vowel_ratio': vowel_ratio
                }
            }
        
        # Check length
        if len(domain_name) > self.length_threshold:
            return {
                'type': 'dga_detected',
                'domain': domain,
                'reason': f'Unusually long domain name ({len(domain_name)} chars)',
                'confidence': min(1.0, len(domain_name) / 40.0),
                'indicators': {
                    'entropy': entropy,
                    'length': len(domain_name),
                    'consonant_ratio': consonant_ratio,
                    'vowel_ratio': vowel_ratio
                }
            }
        
        return None
    
    def detect_dns_tunneling(self, device_mac: str, domain: str, query_type: str) -> Optional[Dict]:
        """
        Detect DNS tunneling (data exfiltration via DNS).
        
        Returns:
            Dict with detection details if tunneling suspected, None otherwise
        """
        parts = self.extract_domain_parts(domain)
        subdomain = parts['subdomain']
        
        # Check for very long subdomains (data encoded in subdomain)
        if len(subdomain) > self.subdomain_length_threshold:
            return {
                'type': 'dns_tunneling',
                'domain': domain,
                'device': device_mac,
                'reason': f'Very long subdomain ({len(subdomain)} chars) - possible data exfiltration',
                'confidence': min(1.0, len(subdomain) / 100.0),
                'indicators': {
                    'subdomain_length': len(subdomain),
                    'query_type': query_type
                }
            }
        
        # Track query rate
        current_time = datetime.now()
        self.device_query_times[device_mac].append(current_time)
        self.device_query_counts[device_mac] += 1
        
        # Remove old timestamps (older than 1 minute)
        cutoff = current_time - timedelta(minutes=1)
        self.device_query_times[device_mac] = [
            t for t in self.device_query_times[device_mac] if t > cutoff
        ]
        
        query_rate = len(self.device_query_times[device_mac])
        
        if query_rate > self.query_rate_threshold:
            return {
                'type': 'dns_tunneling',
                'domain': domain,
                'device': device_mac,
                'reason': f'High query rate ({query_rate}/min) - possible tunneling',
                'confidence': min(1.0, query_rate / 200.0),
                'indicators': {
                    'query_rate': query_rate,
                    'threshold': self.query_rate_threshold,
                    'query_type': query_type
                }
            }
        
        # Check for excessive TXT record queries (common in tunneling)
        if query_type == 'TXT':
            txt_count = sum(
                1 for t in self.device_query_times[device_mac]
                if t > current_time - timedelta(minutes=5)
            )
            
            if txt_count > self.txt_record_threshold:
                return {
                    'type': 'dns_tunneling',
                    'domain': domain,
                    'device': device_mac,
                    'reason': f'Excessive TXT queries ({txt_count} in 5 min) - possible data exfiltration',
                    'confidence': min(1.0, txt_count / 50.0),
                    'indicators': {
                        'txt_query_count': txt_count,
                        'time_window': '5 minutes',
                        'query_type': query_type
                    }
                }
        
        return None
    
    def analyze_dns_query(self, device_mac: str, domain: str, query_type: str = 'A') -> List[Dict]:
        """
        Analyze a DNS query for anomalies.
        
        Args:
            device_mac: MAC address of querying device
            domain: Queried domain name
            query_type: DNS query type (A, AAAA, TXT, MX, etc.)
        
        Returns:
            List of detected anomalies
        """
        alerts = []
        
        # Check for DGA
        dga_alert = self.detect_dga_domain(domain)
        if dga_alert:
            alerts.append(dga_alert)
        
        # Check for DNS tunneling
        tunnel_alert = self.detect_dns_tunneling(device_mac, domain, query_type)
        if tunnel_alert:
            alerts.append(tunnel_alert)
        
        # Log if alerts generated
        if alerts:
            logger.warning(f"DNS anomalies detected for {device_mac}: {len(alerts)} alerts")
            for alert in alerts:
                logger.warning(f"  - {alert['type']}: {alert['domain']} ({alert['reason']})")
        
        return alerts
    
    def get_statistics(self) -> Dict:
        """Get current detection statistics."""
        return {
            'tracked_devices': len(self.device_query_counts),
            'total_queries': sum(self.device_query_counts.values()),
            'cache_size': len(self.domain_cache),
            'thresholds': {
                'entropy': self.entropy_threshold,
                'consonant_ratio': self.consonant_ratio_threshold,
                'vowel_ratio': self.vowel_ratio_threshold,
                'domain_length': self.length_threshold,
                'subdomain_length': self.subdomain_length_threshold,
                'query_rate': self.query_rate_threshold,
                'txt_records': self.txt_record_threshold
            }
        }


# Example usage and testing
if __name__ == '__main__':
    detector = DNSAnomalyDetector()
    
    # Test cases
    test_queries = [
        ('00:1A:2B:3C:4D:5E', 'google.com', 'A'),  # Normal
        ('00:1A:2B:3C:4D:5E', 'facebook.com', 'A'),  # Normal
        ('00:1A:2B:3C:4D:5E', 'xkjdf8s9d7f6g.com', 'A'),  # DGA (high entropy)
        ('00:1A:2B:3C:4D:5E', 'qwrtypsdfgh.net', 'A'),  # DGA (no vowels)
        ('00:1A:2B:3C:4D:5E', 'verylongsubdomainwithlotsofdataencodedinit.evil.com', 'TXT'),  # Tunneling
    ]
    
    print("="*80)
    print("DNS ANOMALY DETECTOR - TEST RESULTS")
    print("="*80)
    
    for device_mac, domain, query_type in test_queries:
        alerts = detector.analyze_dns_query(device_mac, domain, query_type)
        
        if alerts:
            print(f"\n🚨 ALERT: {domain}")
            print(f"   Device: {device_mac}")
            for alert in alerts:
                print(f"   Type: {alert['type']}")
                print(f"   Reason: {alert['reason']}")
                print(f"   Confidence: {alert['confidence']:.2%}")
        else:
            print(f"✅ Normal: {domain}")
    
    print("\n" + "="*80)
    print("STATISTICS:")
    stats = detector.get_statistics()
    for key, value in stats.items():
        print(f"  {key}: {value}")
    print("="*80)